### PR TITLE
Add function tests

### PR DESCRIPTION
**Pull request by lifeiscontent**
this is the revamped theme for fortitude.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@agius @wnadeau

**Comment by wnadeau** [comment]
<3 tests this is awesome

**Comment by agius** [comment]
:+1: :shipit:

**Comment by wnadeau** [comment]
trying to cut a release this morning, just gonna merge and see if the build fails. pew pew pew

**Comment by wnadeau** [comment]
also it looks like tests and no API changes

**Pull request merged**
