### PR TITLE
Stop using rem units unless its font-size or letter-spacing

### PR DESCRIPTION
**Pull request by lifeiscontent**
Bump fortitude version to 0.8.0

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@agius @wnadeau

**Comment by agius** [comment]
I thought rem units was half the point of Fortitude XD What's the benefit of using px? And is that reasonably dpi-independent?

**Comment by lifeiscontent** [comment]
@agius this isn't going to get merged just yet. I'm waiting on sasda's feedback for what he visually wants our app to look like. this was just to show 1 of the options.

**Comment by lifeiscontent** [comment]
@agius what do you think about providing a configuration option to use either rem, px, or a mixture of things depending on the context.

Most people today use rem for font and px for everything else

**Pull request closed without merging**
